let FETCH_BOARD_DATA="FETCH_BOARD_DATA";
let FETCH_BOARD_DATA_SUCCESS="FETCH_BOARD_DATA_SUCCESS";
let FETCH_BOARD_DATA_ERROR="FETCH_BOARD_DATA_ERROR";

export {FETCH_BOARD_DATA,FETCH_BOARD_DATA_SUCCESS,FETCH_BOARD_DATA_ERROR} 